language: php

os:
  - linux

dist: bionic

services:
  - mysql
  - postgresql
  - docker

addons:
  postgresql: "9.6"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.nvm

php:
 - 7.3

env:
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=master

jobs:
  include:
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache 
  - moodle-plugin-ci grunt || true
  - moodle-plugin-ci phpunit --coverage-text --coverage-clover
  - moodle-plugin-ci behat
  - moodle-plugin-ci behat --profile chrome
  - php /home/travis/build/moodle/admin/tool/behat/cli/init.php -a="classic"
  - moodle-plugin-ci behat --suite="classic"
  - moodle-plugin-ci behat --suite="classic" --profile chrome
  - moodle-plugin-ci behat --suite="classic" --profile chrome --dump /home/travis/build/moodle/blocks/admin_bookmarks
  - /home/travis/build/moodle/vendor/bin/phpunit "provider_testcase" /home/travis/build/moodle/privacy/tests/provider_test.php
  - /home/travis/build/moodle/vendor/bin/phpunit "tool_dataprivacy_expired_contexts_testcase" /home/travis/build/moodle/admin/tool/dataprivacy/tests/expired_contexts_test.php

after_success:
  - moodle-plugin-ci coveralls-upload
