name: Cron

on:
  schedule:
    - cron: "5 10 9 * *"

jobs:
  cron:
    name: Cron
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        moodle-branch: ['main']
        php: ['8.3']
        database: ['pgsql']

    steps:
      - name: checkout plugin
        uses: actions/checkout@v5
        with:
          path: this-plugin

      - name: setup pgsql
        uses: m4nu56/postgresql-action@v1
        with:
          postgresql version: 16
          postgresql user: test
          postgresql password: test

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: max_input_vars=5000
          coverage: pcov

      - name: composer
        run: |
           composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci
           echo $(cd ci/bin; pwd) >> $GITHUB_PATH
           echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
           sudo locale-gen en_AU.UTF-8

      - name: install Moodle
        run: moodle-plugin-ci install  --db-host=127.0.0.1 --db-type=pgsql --db-user=test --db-pass=test --plugin this-plugin
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: phplint
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi phplint

      - name: phpmd
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi phpmd

      - name: phpdoc
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi phpdoc

      - name: codechecker
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi codechecker

      - name: validate
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi validate

      - name: savepoints
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi savepoints

      - name: grunt
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi grunt

      - name: mustache
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi mustache

      - name: phpunit
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi phpunit --testdox --coverage-text --coverage-clover

      - name: behat
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi behat --profile=chrome
