name: Tests

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: --health-cmd="pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
        ports:
          - 3306:3306

    strategy:
      fail-fast: false
      matrix:
        moodle-branch: ['MOODLE_400_STABLE', 'MOODLE_401_STABLE', 'MOODLE_402_STABLE', 'master']
        php: ['8.0']
        database: ['mariadb', 'pgsql']
        include:
          - php: '8.1'
            moodle-branch: 'MOODLE_402_STABLE'
            database: 'pgsql'
          - php: '7.4'
            moodle-branch: 'MOODLE_400_STABLE'
            database: 'pgsql'

    steps:
      - name: checkout plugin
        uses: actions/checkout@v3
        with:
          path: this-plugin

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pgsql, mysqli, gd, xmlrpc, zip
          ini-values: max_input_vars=5000
          coverage: xdebug

      - name: npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-${{ matrix.php }}-${{ matrix.moodle-branch }}-${{ matrix.database }}-cache
          restore-keys: |
            node-${{ matrix.php }}-${{ matrix.moodle-branch }}-${{ matrix.database }}-cache

      - name: composer
        run: |
           composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
           echo $(cd ci/bin; pwd) >> $GITHUB_PATH
           echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
           sudo locale-gen en_AU.UTF-8

      - name: install Moodle
        run: moodle-plugin-ci --ansi install --db-host=127.0.0.1 --plugin this-plugin
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: phplint
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phplint

      - name: phpcpd
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpcpd

      - name: phpmd
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpmd

      - name: phpdoc
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpdoc

      - name: codechecker
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi codechecker

      - name: validate
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi validate

      - name: savepoints
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi savepoints

      - name: grunt
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi grunt

      - name: mustache
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi mustache

      - name: phpunit
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpunit --coverage-text --coverage-clover

      - name: firefox
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi behat
      
      - name: chrome
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi behat --profile chrome

      - name: firefox classic
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi behat --suite classic
      
      - name: chrome classic
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi behat --suite classic --profile=chrome

      - name: coveralls
        if: ${{ always() }}
        run: moodle-plugin-ci coveralls-upload
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
