name: Tests

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: --health-cmd="pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
        ports:
          - 3306:3306

    strategy:
      fail-fast: false
      matrix:
        moodle-branch: ['MOODLE_311_STABLE']
        php: ['8.0', '7.4']
        database: ['mariadb', 'pgsql']
        include:
        - php: 7.4
          moodle-branch: MOODLE_310_STABLE
          database: mariadb
        - php: 7.4
          moodle-branch: MOODLE_39_STABLE
          database: mariadb

    steps:
      - name: checkout plugin
        uses: actions/checkout@v2
        with:
          path: this-plugin

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pgsql, mysqli, gd, xmlrpc, zip
          ini-values: max_input_vars=5000
          coverage: xdebug

      - name: composer
        run: |
           composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
           echo $(cd ci/bin; pwd) >> $GITHUB_PATH
           echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
           sudo locale-gen en_AU.UTF-8
           sed -i 's/phpdbg -d memory_limit=-1 -qrr//g' ci/src/Command/PHPUnitCommand.php

      - name: install Moodle
        run: moodle-plugin-ci --ansi install --db-host=127.0.0.1 --plugin this-plugin
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}
      
      - name: phplint
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phplint

      - name: phpcpd
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpcpd

      - name: phpmd
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpmd

      - name: phpdoc
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpdoc

      - name: codechecker
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi codechecker

      - name: validate
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi validate

      - name: savepoints
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi savepoints

      - name: grunt
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi grunt

      - name: mustache
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi mustache

      - name: phpunit
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpunit --coverage-text

      - name: firefox
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi behat
      
      - name: chrome
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi behat --profile chrome

      - name: firefox classic
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi behat --suite classic
      
      - name: chrome classic
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi behat --suite classic --profile=chrome

      - name: admin bookmarks
        if: ${{ always() }}
        run: php admin/tool/behat/cli/run.php --tags=@block_admin_bookmarks --suite=${{ matrix.suite }}
        working-directory: moodle

      - name: privacy
        if: ${{ always() }}
        run: vendor/bin/phpunit --colors --no-coverage --testsuite tool_dataprivacy_testsuite,tool_policy_testsuite,core_privacy_testsuite
        working-directory: moodle
